# Generated by Django 4.0.6 on 2022-08-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_monday',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_tuesday',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
