# Generated by Django 4.0.6 on 2022-08-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_menu_friday_restaurant_menu_saturday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='menu_monday',
            field=models.TextField(blank=True, default='Menu was not published yet'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_thursday',
            field=models.TextField(blank=True, default='Menu was not published yet'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_tuesday',
            field=models.TextField(blank=True, default='Menu was not published yet'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_wednesday',
            field=models.TextField(blank=True, default='Menu was not published yet'),
        ),
    ]
