# Generated by Django 4.0.6 on 2022-08-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_menu_monday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='menu_friday',
            field=models.TextField(blank=True, default='Menu was not published yet'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_saturday',
            field=models.TextField(blank=True, default='Menu was not published yet'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_sunday',
            field=models.TextField(blank=True, default='Menu was not published yet'),
        ),
    ]
